FROM node:lts-bookworm-slim AS base

FROM base AS deps
WORKDIR /app

RUN npm install -g pnpm

COPY package*.json pnpm-lock.yaml ./
RUN pnpm install

FROM deps AS build
WORKDIR /app
COPY . .
RUN node ace build

FROM base AS production
WORKDIR /app
ENV NODE_ENV=production

RUN npm install -g pnpm

COPY --from=build /app/build ./
RUN pnpm install --prod

EXPOSE 3333
CMD ["node", "bin/server.js"]