/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Authenticate: () => import('#controllers/auth/authenticate_controller'),
  },
  clients: {
    Client: () => import('#controllers/clients/client_controller'),
  },
  gateways: {
    Gateways: () => import('#controllers/gateways/gateways_controller'),
  },
  purchase: {
    Purchase: () => import('#controllers/purchase/purchase_controller'),
  },
  transactions: {
    Transactions: () => import('#controllers/transactions/transactions_controller'),
  },
  users: {
    Users: () => import('#controllers/users/users_controller'),
  },
}
