import './routes/public/authenticate_routes.ts'
import './routes/public/purchase_routes.ts'
import './routes/private/gateways_routes.ts'
import './routes/private/transactions_routes.ts'
import './routes/private/clients_routes.ts'
import './routes/private/users_routes.ts'
import './routes/private/products_routes.ts'
